apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: haingyen/backend:61b3f428e68c98910b7b9bba59d0efb2d8773074
        ports:
        - containerPort: 5001
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo-service:27017/mydb"
        - name: PORT
          value: "5001"
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 5001
    targetPort: 5001