apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  MONGO_INITDB_DATABASE: "mydb"
  NODE_ENV: "production"
  PORT: "5001"
  MONGODB_CONNECTIONSTRING: "mongodb://mongodb:27017/${MONGO_INITDB_DATABASE}"